### ISSUE TITLE
sometimes errors are not properly formatted

### ISSUE THREAD

**Issue by fernandezpablo85** [ArpNetworking/sbt-typescript#8]
full stacktrace

``````
spray.json.DeserializationException: Expected String as JsString, but got {"messageText":"Type '{ 'id': number; 'label': any; }' is not assignable to type 'Practice'.","category":1,"code":2322,"next":{"messageText":"Types of property 'id' are incompatible.","category":1,"code":2326,"next":{"messageText":"Type 'number' is not assignable to type 'string'.","category":1,"code":2322}}}
    at spray.json.package$.deserializationError(package.scala:23)
    at spray.json.BasicFormats$StringJsonFormat$.read(BasicFormats.scala:126)
    at spray.json.BasicFormats$StringJsonFormat$.read(BasicFormats.scala:119)
    at spray.json.JsValue.convertTo(JsValue.scala:32)
    at com.typesafe.sbt.jse.SbtJsTask$JsTaskProtocol$LineBasedProblemFormat$$anonfun$read$4.apply(SbtJsTask.scala:110)
    at com.typesafe.sbt.jse.SbtJsTask$JsTaskProtocol$LineBasedProblemFormat$$anonfun$read$4.apply(SbtJsTask.scala:110)
    at scala.Option.fold(Option.scala:157)
    at com.typesafe.sbt.jse.SbtJsTask$JsTaskProtocol$LineBasedProblemFormat$.read(SbtJsTask.scala:110)
    at com.typesafe.sbt.jse.SbtJsTask$JsTaskProtocol$LineBasedProblemFormat$.read(SbtJsTask.scala:105)
    at spray.json.JsValue.convertTo(JsValue.scala:32)
    at spray.json.CollectionFormats$$anon$4$$anonfun$read$4.apply(CollectionFormats.scala:89)
    at spray.json.CollectionFormats$$anon$4$$anonfun$read$4.apply(CollectionFormats.scala:89)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at spray.json.CollectionFormats$$anon$4.read(CollectionFormats.scala:89)
    at spray.json.CollectionFormats$$anon$4.read(CollectionFormats.scala:86)
    at spray.json.ProductFormats$class.fromField(ProductFormats.scala:47)
    at com.typesafe.sbt.jse.SbtJsTask$JsTaskProtocol$.fromField(SbtJsTask.scala:92)
    at spray.json.ProductFormatsInstances$$anon$2.read(ProductFormatsInstances.scala:56)
    at spray.json.ProductFormatsInstances$$anon$2.read(ProductFormatsInstances.scala:46)
    at spray.json.JsValue.convertTo(JsValue.scala:32)
    at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeSourceFilesJs$1$$anonfun$7.apply(SbtJsTask.scala:225)
    at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeSourceFilesJs$1$$anonfun$7.apply(SbtJsTask.scala:224)
    at scala.collection.LinearSeqOptimized$class.foldLeft(LinearSeqOptimized.scala:111)
    at scala.collection.immutable.List.foldLeft(List.scala:84)
    at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeSourceFilesJs$1.apply(SbtJsTask.scala:223)
    at com.typesafe.sbt.jse.SbtJsTask$$anonfun$com$typesafe$sbt$jse$SbtJsTask$$executeSourceFilesJs$1.apply(SbtJsTask.scala:221)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:206)
    at scala.util.Try$.apply(Try.scala:161)
    at scala.util.Success.map(Try.scala:206)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
    at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)```
``````

**Comment by BrandonArp** [comment]
Very interesting.  It looks like the diagnostic coming back from the compiler isn't what is expected for the debug output.  Can you send me a short snippet of code typescript code that will repro this?

**Comment by fernandezpablo85** [comment]
Sure, I'll try to isolate the smallest possible case and attach it.

**Comment by fernandezpablo85** [comment]
This seems to trigger it 

``` typescript
interface Stuff {
  id: number;
  foo: string;
  bar: string;
}

var lotsOfStufff: Stuff[] = []

lotsOfStufff.push({ 'id': 1, 'foo': 'value' });
```

**Comment by BrandonArp** [comment]
Thank you @fernandezpablo85 for the repro case.  As an FYI, this was caused by the messageText of a diagnostic message being an object (which was actually a linked list of error messages).

**Comment by fernandezpablo85** [comment]
great! is `0.1.6-SNAPSHOT` pushed to central?

**Comment by BrandonArp** [comment]
0.1.6 was just released to central.  The artifact should be there in about 10 minutes or so.
